<?php
/**
 * Created by PhpStorm.
 * User: bruss5
 * Date: 3/11/2019
 * Time: 8:16 PM
 */

require_once "lib/ReportsDatabase.php";

const DEBUG_MODE = true;

if((isset($_POST['action']) && $_POST['action'] === "Cancel Report")&&(isset($_POST['id']) && !empty($_POST['id']))){
    CancelReportByKey(GetDBConnection(),$_POST['id'],$_SERVER['REMOTE_ADDR']);
    header("Location:report_cancelled.html");
    die("Cancelled");
}///todo fix
// assume form is filled
if((isset($_POST['id']) && !empty($_POST['id']))/* &&
    (isset($_POST['details']) && !empty($_POST['details']))*/){
    if(CompleteReportByKey(GetDBConnection(), $_POST['id'],$_POST['category'], $_POST['details'], $_SERVER['REMOTE_ADDR'])){
        header("Location:report_success.html");
        die("Report submitted. Thanks!");
    } else {
        header("Location:invalid_key.html");
        die("complete failed");
    }
}

if(!isset($_GET['id']) || empty($_GET['id'])){
    //header("Location:invalid_key.html");
    die("Invalid token.");
} else {
    $form_id = $_GET['id'];

    $report = GetReportByKey(GetDBConnection(), $form_id);

    if(is_null($report)){
        header("Location:invalid_key.html");
        die("Invalid token.");
    } else {
        // valid. check if form is completed
        if(DEBUG_MODE){
            echo("<!------------");
            print_r($report);
            echo("------------!>");
        }
    }
}

$categories = GetReportCategories(GetDBConnection());

?>
<link rel="stylesheet" href="css/bootstrap.min.css">

<form action="" method="post">
    <input type="hidden" name="id" value="<?php echo $form_id;?>"/>
    <label>Your Username:
        <input type="text" readonly value="<?php echo $report['reporter_username'];?>">
    </label>
    <br/>
    <label>Their Username:
        <input type="text" readonly value="<?php echo $report['reported_username'];?>">
    </label>
    <br/>
    <label>Category:
        <select name="category">
            <!--- begin autogenerated select -->
            <?php
                foreach ($categories as $category){
                    echo("<optgroup label=\"".$category['category_display_name']."\">");
                    $subcategories = explode("|",$category['subcategories']);
                    foreach ($subcategories as $subcategory){
                        echo("<option value=\"".$category['category_identifier'].".".$subcategory."\">$subcategory</option>");
                    }
                    echo("</optgroup>");
                }
            ?>
            <!--- end autogenerated select -->
        </select>
    </label>
    <br/>
    <textarea class="" name="details" placeholder="Tell us what happened." rows="10"></textarea>
    <br/>
    <input type="submit" class="btn-danger" value="Cancel Report" name="action"/><input type="submit" class="btn-warning" value="Complete Report"  name="action"/>
</form>

