<?php
/**
 * Created by PhpStorm.
 * User: bruss5
 * Date: 3/11/2019
 * Time: 8:16 PM
 */

require_once "lib/ReportsDatabase.php";

const DEBUG_MODE = false;

if((isset($_POST['action']) && $_POST['action'] === "Cancel Report")&&(isset($_POST['id']) && !empty($_POST['id']))){
    CancelReportByKey(GetDBConnection(),$_POST['id'],$_SERVER['REMOTE_ADDR']);
    header("Location:report_cancelled.html");
    die("Cancelled");
}

if((isset($_POST['id']) && !empty($_POST['id'])) &&
    (isset($_POST['details']) && !empty($_POST['details']))){
    if(CompleteReportByKey(GetDBConnection(), $_POST['id'],$_POST['category'], $_POST['details'], $_SERVER['REMOTE_ADDR'])){
        header("Location:report_success.html");
        die("Report submitted. Thanks!");
    } else {
        header("Location:report_cancelled.html");
        die("complete failed");
    }
}

if(!isset($_GET['id']) || empty($_GET['id'])){
    //header("Location:invalid_key.html");
    die("Invalid token.");
} else {
    $form_id = $_GET['id'];

    $report = GetReportByKey(GetDBConnection(), $form_id);

    if(is_null($report)){
        header("Location:invalid_key.html");
        die("Invalid token.");
    } else {
        // valid. check if form is completed
        if(DEBUG_MODE){
            echo("<!------------");
            print_r($report);
            echo("------------!>");
        }
    }
}

$categories = GetReportCategories(GetDBConnection());

?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>New Report</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>

        /** {*/
            /*line-height: 1.2;*/
            /*margin: 0;*/
        /*}*/

        html {
            color: #888;
            display: table;
            font-family: sans-serif;
            height: 100%;
            text-align: center;
            width: 100%;
        }

        body {
            display: table-cell;
            vertical-align: middle;
            margin: 2em auto;
        }

        h1 {
            color: #555;
            font-size: 2em;
            font-weight: 400;
        }

        p {
            margin: 0 auto;
            width: 280px;
        }

        @media only screen and (max-width: 280px) {

            body, p {
                width: 95%;
            }

            h1 {
                font-size: 1.5em;
                margin: 0 0 0.3em;
            }

        }

    </style>
</head>
<body class="media-body" style="background-color:lightblue">
    <h1>New Report</h1><br/>
    <form action="" method="post">
        <input type="hidden" name="id" value="<?php echo $form_id;?>"/>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Their Username:</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" value="<?php echo $report['reported_username'];?>">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Your Username:</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" value="<?php echo $report['reporter_username'];?>">
            </div>
        </div>

        <div class="form-group row">
        <label class="col-sm-2 col-form-label">Report Category:</label>
        <select class="form-inline" name="category">
            <option value="none_set" selected>Choose category...</option>
            <!--- begin autogenerated select -->
            <?php
                foreach ($categories as $category){
                    echo("<optgroup label=\"".$category['category_display_name']."\">");
            $subcategories = explode("|",$category['subcategories']);
            foreach ($subcategories as $subcategory){
            echo("<option value=\"".$category['category_identifier'].".".$subcategory."\">$subcategory</option>");
            }
            echo("</optgroup>");
            }
            ?>
            <!--- end autogenerated select -->
        </select>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Report Details: </label>
            <div class="col-sm-10">
                <textarea placeholder="Tell us what happened..." id="report" name="details" class="form-horizontal" rows="8" cols="120"></textarea><p class="text-muted" id="count">Characters: 0</p>
            </div>
        </div>

        <div class="form-group row">
            <input type="submit" class="btn btn-danger" value="Cancel Report" name="action"/> <span></span><input type="submit" id="submitbtn" class="btn btn-warning" value="Complete Report"  name="action"/>
        </div>

    </form>
</body>
</html>
<script>
    document.getElementById('report').onkeyup = function () {
        document.getElementById('count').innerHTML = "Characters: " + this.value.length;
    };
</script>
<!-- IE needs 512+ bytes: http://blogs.msdn.com/b/ieinternals/archive/2010/08/19/http-error-pages-in-internet-explorer.aspx -->
<footer style="position:fixed;bottom:0;left:0;right:0;height:60px;" class="panel-footer">
    <p style="width: 90%" class="panel-footer">WebReporter Copyright Brady Russell 2019. Thank you to <a href="https://crafatar.com">Crafatar</a> for providing avatars.</p>
</footer>