

<?php
/**
 * Created by PhpStorm.
 * User: bruss5
 * Date: 3/12/2019
 * Time: 9:26 AM
 */

require_once "../lib/RequireManager.php";
$categories = GetReportCategories(GetDBConnection());

const DEBUG_MODE = true;

$selected_category = null;

if(isset($_POST['delete_category']) && !empty($_POST['delete_category'])){
    DeleteReportCategory(GetDBConnection(), $_POST['delete_category']);
    header("Location:categories.php");
    die("deleted");
}

if(isset($_POST['save_category']) && !empty($_POST['save_category'])){
    SetReportCategoryContents(GetDBConnection(), $_POST['save_category'], $_POST['save_subcategories']);
    header("Location:categories.php");
    die("saved");
}

if(isset($_POST['edit_category']) && !empty($_POST['edit_category'])){
    foreach ($categories as $category){
        if($category['category_identifier'] === $_POST['edit_category']) $selected_category = $category;
    }
}

if(isset($_POST['new_category']) && !empty($_POST['new_category'])){
    /* create it */
    CreateReportCategory(GetDBConnection(), $_POST['new_category']);
    $categories = GetReportCategories(GetDBConnection());
    foreach ($categories as $category){
        if($category['category_display_name'] === $_POST['new_category']) $selected_category = $category;
    }
}

?>
<link rel="stylesheet" href="../css/bootstrap.min.css">

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.php">JahCraft.VIP Reports Manager</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <form class="navbar-form navbar-right" role="form" method="post" action="">
                <div class="form-group">
                    <input name="new_category" type="text" placeholder="Create New Category..." class="form-control">
                </div>
                <button type="submit" class="btn btn-success">Add</button>
            </form>

            <form class="navbar-form navbar-right" role="form" method="post" action="">
                <div class="form-group">
                    <label class="label">Modify Existing Category:
                        <select class="form-control" name="edit_category">
                            <!--- begin autogenerated select -->
                            <?php
                            foreach ($categories as $category){
                                echo("<option value='".$category['category_identifier']."'>".$category['category_display_name']."</option>");
                            }
                            ?>
                            <!--- end autogenerated select -->
                        </select>
                    </label>
                </div>
                <button type="submit" class="btn btn-info">Edit</button>
            </form>


            <form class="navbar-form" role="form" method="get" action="queue.php">
                <button type="submit" class="btn btn-warning">My Queue</button>
            </form>
        </div><!--/.navbar-collapse -->
    </div>
</nav>
<br/><br/><br/>

<!--- if selected cat != null -->
<?php if(is_null($selected_category)) die("<footer class=\"panel-footer\">
    <p class=\"panel-footer\">WebReporter Copyright Brady Russell 2019. Thank you to <a href=\"https://crafatar.com\">Crafatar</a> for providing avatars.</p>
</footer>"); ?>

<table class="table table-striped table-dark table-hover">
    <thead>
    <tr>
        <th scope="col">Category Name</th>
        <th scope="col">Subcategories</th>
    </tr>
    </thead>
    <form action="" method="post">
        <tbody>
            <tr>
                <td><input type="hidden" name="save_category" value="<?php echo($selected_category['category_identifier']); ?>">
                    <?php
                    echo($selected_category['category_display_name']);
                    ?>
                </td>
                <td><label>Separated by a | character.
                        <textarea name="save_subcategories" rows="8" cols="32"><?php echo($selected_category['subcategories']); ?></textarea>
                    </label>
                </td>
            </tr><td>
                <button type="submit" class="btn-lg btn-primary">Save Category</button><br/></td></form><td>
            <form onsubmit="return confirm('Are you sure you want to delete this category? This is irreversible.');" action="" method="post">
                <button type="submit" class="btn-lg btn-danger" name="delete_category" value="<?php echo($selected_category['category_identifier']);?>">Delete Category</button>
            </form></td>
            </tr>
        </tbody>

</table>





<footer style="position:fixed;bottom:0;left:0;right:0;height:60px;" class="panel-footer">
    <p class="panel-footer">WebReporter Copyright Brady Russell 2019. Thank you to <a href="https://crafatar.com">Crafatar</a> for providing avatars.</p>
</footer>




